### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit.delta_generator'; 'streamlit' is not a package

### ISSUE THREAD

**Issue by IvanReznikov** [ur-whitelab/chemcrow-public#10] opened 2023-11-02 11:36 UTC
I'm getting ModuleNotFoundError: No module named 'streamlit.delta_generator'; 'streamlit' is not a package
when trying to init ChemCrow

![image](https://github.com/ur-whitelab/chemcrow-public/assets/25007854/cc99117c-d077-49ac-8386-abd72431dae6)

**Comment by tclaiserver** [comment] 2023-12-29 06:51
Hey, were you able to solve this issue? I was facing the same issue.

**Comment by doncamilom** [comment] 2024-01-10 23:19
Hi thanks for raising the issue. Can you please provide more details on the platform you tried this on? Is it a linux/macos machine?

**Comment by doncamilom** [comment] 2024-02-29 12:20
I'm closing the issue as it seems solved, can't reproduce it on my side and everything looks correct.

My best guess is there's been installation errors.

**Closed by doncamilom** 2024-02-29 12:20 UTC
